Первое задание
sergey-berezin/441_golovanov pull request #2
Opened 2021-10-05 09:55 UTC by rassel1976

Пока не работает остановка тасков, будет немного позже.

2021-10-05 09:56 UTC, rassel1976 commented
Запускать YoloC

2021-10-06 07:02 UTC, sergey-berezin requested changes

2021-10-06 07:02 UTC, sergey-berezin commented on ParMLcs.cs
> +            task3.Wait();
Wait надо убрать.

2021-10-06 07:02 UTC, sergey-berezin commented on ParMLcs.cs
> +        public List<imageRes> processFolder(string folder)
Надо предусмотреть возможность получения результатов по мере распознавания и остановки распознавания (CancellationToken)

2021-11-30 14:26 UTC, closed without merging